#!/bin/bash

download_graded_book_by_url() {
	url=$1
	page=$(curl -s "$url")
	zipurl=$(
		pup '#modal_audio > div > div > div.modal-body > div > a attr{href}' <<<"$page" | sed 's|^|https://www.eligradedreaders.com|g'
	)
	title=$(
		pup "#akeeba-renderjoomla > div > div.row-height.mk-1 > div.col-lg-7.col-md-6.col-sm-12.col-xs-12 > div:nth-child(1) > h2 > b text{}" <<<"$page"
	)

	cover=$(
		pup "#akeeba-renderjoomla > div > div.row-height.mk-1 > div.col-lg-5.col-md-6.col-sm-12.col-xs-12 > div > span > img attr{href}" <<<"$page"
	)
	echo "$cover"
	level="$(
		pup '#akeeba-renderjoomla > div > div.row-height.mk-1 > div.col-lg-7.col-md-6.col-sm-12.col-xs-12 > div:nth-child(2) > button:nth-child(1) text{}' <<<"$page" | xargs
	)"
	detail="$(
		pup "#descrizione > div > div:nth-child(1) > strong text{}" <<<"$page"
	)"
	mkdir "$title"
	wget -q $zipurl -O /tmp/wget && mv /tmp/wget "$title/$title.zip"
	(
		cd "$title"
		jq -n --arg title "$title" --arg detail "$detail" --arg level "$level" '{"title": $title, "detail": $detail, "level": $level}' >"${title}.json"
		# unzip file
		unzip -o *.zip -d "${title}_splitted"
	)
}

download_graded_books() {
	urls="$(curl -s "https://www.eligradedreaders.com/english?productfilter_ids[]=50&productfilter_ids[]=58" | pup '#akeeba-renderjoomla > div > div > div.jb-product-section.col-sm-9 > div.j2store-products-row.row-0.nrow > div > div > div.j2store-product-item-gird-info > div > div > div.j2store_product_content_block > div > h2 > a attr{href}' | sed 's|^|https://www.eligradedreaders.com|g')"
	for url in $urls; do
		download_graded_book_by_name $url
	done
}

download_book() {
	book=$1
	output=$(curl -s "https://english-e-reader.net$book")
	words=$(grep --line-buffered -E "^words: " <<<$output | awk '{print $2}')
	bookname=$(echo $book | sed 's|/book/||')
	echo "$words $bookname"
	mkdir "$bookname"
	wget -q "https://english-e-reader.net/download?link=$bookname&format=epub" -O /tmp/wget && mv /tmp/wget "$bookname/$bookname.epub"
	wget -q "https://english-e-reader.net/download?link=$bookname&format=mp3" -O /tmp/wget && mv /tmp/wget "$bookname/$bookname.mp3"
	wget -q "https://english-e-reader.net/download?link=$bookname&format=cue" -O /tmp/wget && mv /tmp/wget "$bookname/$bookname.cue"
	wget -q "https://english-e-reader.net/download?link=$bookname&format=mp3zip" -O /tmp/wget && mv /tmp/wget "$bookname/$bookname.zip"
	# /download?link=body-on-the-rocks-denise-kirby&format=
	python3 fetch_meta_data.py -t $bookname >"${bookname}/metadata.json"
	(
		cd "$bookname"
		# unzip file
		unzip -o *.zip -d "${bookname}_splitted"
		# alias m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt sandreas/m4b-tool:latest'
		docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt sandreas/m4b-tool:latest split --audio-format mp3 --audio-bitrate 96k --audio-channels 1 --audio-samplerate 22050 "${bookname}.mp3"
	)
}

download_all_book() {
	level=$1
	books=($(curl -s "https://english-e-reader.net/level/$level" | grep "/book/.*>" | sed 's/<a.*="//' | sed 's/">//'))

	# | xargs -n 1 curl -s | grep --line-buffered -E "^words: "
	for book in "${books[@]}"; do
		download_book $book
	done
}
