#!/bin/bash

download_book() {
	book=$1
	output=$(curl -s "https://english-e-reader.net$book")
	words=$(grep --line-buffered -E "^words: " <<<$output | awk '{print $2}')
	bookname=$(echo $book | sed 's|/book/||')
	echo "$words $bookname"
	mkdir "$bookname"
	wget -q "https://english-e-reader.net/download?link=$bookname&format=epub" -O /tmp/wget && mv /tmp/wget "$bookname/$bookname.epub"
	wget -q "https://english-e-reader.net/download?link=$bookname&format=mp3" -O /tmp/wget && mv /tmp/wget "$bookname/$bookname.mp3"
	wget -q "https://english-e-reader.net/download?link=$bookname&format=cue" -O /tmp/wget && mv /tmp/wget "$bookname/$bookname.cue"
	wget -q "https://english-e-reader.net/download?link=$bookname&format=mp3zip" -O /tmp/wget && mv /tmp/wget "$bookname/$bookname.zip"
	# /download?link=body-on-the-rocks-denise-kirby&format=
}

download_all_book() {
	level=$1
	books=($(curl -s "https://english-e-reader.net/level/$level" | grep "/book/.*>" | sed 's/<a.*="//' | sed 's/">//'))

	# | xargs -n 1 curl -s | grep --line-buffered -E "^words: "
	for book in "${books[@]}"; do
		download_book $book
	done
}
